### PR TITLE
adding url validation both on front end and backend 

### LINKED ISSUE #10: Filter user input
In the current design, user input is not filtered. We want to make sure user inserts a URL only.

### PR DESCRIPTION
**Pull request by sahil-ramagiri**
Fixes #10 

url validation

### CODE REVIEW

**Comment by ksh168** [comment]
Including screenshots/video of final interface/changes in your pull request is a must. Please update your PR.

**Comment by ksh168** [comment]
Including screenshots/video of final interface/changes in your pull request is a must. Please update your PR.

**Comment by ksh168** [comment]
Hey Sahil, I saw your commits, you're proceeding in right direction and "https://" or "http://" are working fine. But let's say if someone adds "github.com" instead of "http://github.com". The code in your PR says it as not URL. Please see to this.
Thanks

**Comment by sahil-ramagiri** [comment]
but how do you redirect page without a protocol? 

image

On redirection without protocol 
image

**Comment by ksh168** [comment]
Hmm. You're correct. I'll merge your PR. Good Work!

**Pull request merged**
