### PR TITLE
Added CSS Asterisks

### LINKED ISSUE #39: Make all the required fields display a red asterisk
Don't do manually, use CSS.

### PR DESCRIPTION
**Pull request by Siddharth1010**
Fixes #39 - Added CSS code for auto asterisks for any labels with id="req".

### CODE REVIEW

**Review by sahil-ramagiri — COMMENTED** [review]
Should have used class right instead of id, as ids should be unique

**Comment by Siddharth1010** [comment]
I have changed it to class

**Comment by Siddharth1010** [comment]
As long as it is just for css id will work fine. But you're right, it's not good practice :)

**Comment by ksh168** [comment]
Hey, nice work. Be sure to mention issue number and attach screenshots on new interface in your PR from next time.

**Comment by ksh168** [comment]
Hey nice work!

**Pull request merged**
