### PR TITLE
Updated gitignore

### PR DESCRIPTION
**Pull request by Antsthebul**
Removed .pyc files from repo and set to untrack cache files, dbs, and env.

### CODE REVIEW

**Comment by ksh168** [comment]
If you remove url_shortener/db.sqlite3 file, the whole thing will break right?

**Comment by Antsthebul** [comment]
No. I just removed the DB from the repo to be untracked by GIT.  'flask run' command creates a DB, becuase of the create_app() inside of the __init__.py

**Comment by ksh168** [comment]
image

When i removed db.sqlite3 file on another branch, i faced this error. Once check

**Comment by Antsthebul** [comment]
oh ok now i see so we would want to keep the DB becuase create_all() is done in the shell.

**Comment by ksh168** [comment]
Yeah

**Comment by ksh168** [comment]
In th meantime I suggest you to complete issue #27

**Pull request closed without merging**
