### PR TITLE
Renamed button and updated readme

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
# Description

Please include a summary of the change and which issue is fixed and how it will affect the project.
Renamed the button on add_link page and updated all the screenshots and also updated the image names in README.md file.

Fixes # (issue)
This PR will fix the issue #36 .

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have attached relevant screenshots/videos
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by ksh168** [comment]
What are these screenshots? How did you manage to get "{{original_url}}" thing there?
Just put a simple URL in the field like "http://www.instagram.com" there.
Refer to the current screenshots in README.

**Comment by 96RadhikaJadhav** [comment]
> What are these screenshots? How did you manage to get "{{original_url}}" thing there?
> Just put a simple URL in the field like "http://www.instagram.com" there.
> Refer to the current screenshots in README.

Oops! Will correct it.

**Comment by 96RadhikaJadhav** [comment]
> > What are these screenshots? How did you manage to get "{{original_url}}" thing there?
> > Just put a simple URL in the field like "http://www.instagram.com" there.
> > Refer to the current screenshots in README.
> 
> Oops! Will correct it.

@ksh168  Can you please check now?

**Comment by ksh168** [comment]
Did you just edit those screenshots to put the new button there 😂😂.
How did you get the exact same URL generated `vddZy7` when you retried it.

**Comment by 96RadhikaJadhav** [comment]
> Did you just edit those screenshots to put the new button there 😂😂.
> How did you get the exact same URL generated `vddZy7` when you retried it.

Yes actually 😂. Because in my system I'm not able to fetch the page where I can try new URL. It is by default fetching the page which I mentioned in first screenshots. So had to do it this way 😂😂.

**Comment by 96RadhikaJadhav** [comment]
> > Did you just edit those screenshots to put the new button there 😂😂.
> > How did you get the exact same URL generated `vddZy7` when you retried it.
> 
> Yes actually 😂. Because in my system I'm not able to fetch the page where I can try new URL. It is by default fetching the page which I mentioned in first screenshots. So had to do it this way 😂😂.

Is it fine though? Because I will not be able to get original screenshots there.

**Comment by ksh168** [comment]
While I appreciate your photo editing skills and creative thinking 😂, I cannot approve this PR.
Try to fix issues with your local system because if you want to work on other issues, you'll need to fix it.
I am closing the issue as well as PR.

**Pull request closed without merging**
