### PR TITLE
added requirements.txt

### PR DESCRIPTION
**Pull request by rutvikpadhiyar000**

### CODE REVIEW

**Comment by ksh168** [comment]
Hey ruthvik, sure I understand adding the requirements.txt file. But all the packages that you have mentioned, are they even used in our project? We don't want packages that we don't need because installing them will only slow our setup process. Please see to this and update your PR. Thanks!

**Comment by rutvikpadhiyar000** [comment]
When you install all packages mentioned in README then other packages are installed as dependencies.

I just installed packages and added `pip freeze` in file

**Comment by rutvikpadhiyar000** [comment]
I think flask_sqlachemy can be removed but since it is a flask app so i didn't do that.

**Comment by ksh168** [comment]
OK we'll see to this later. Let's focus on other issues for now.

**Pull request merged**
