### PR TITLE
Added option for url customization

### PR DESCRIPTION
**Pull request by rutvikpadhiyar000**

### CODE REVIEW

**Comment by ksh168** [comment]
Including screenshots/video of final interface/changes in your pull request is a must. Same was also mentioned in README. Please update your PR.

**Comment by ksh168** [comment]
Good Work @rutvikpadhiyar000 ! This works perfectly.

**Review by sahil-ramagiri — CHANGES_REQUESTED** [review]
1. Not supplying `custom_end` field when testing with curl or other api testers will crash the server, use `request.form.get` method to get default null.
2. Cache files and db files are to be ommitted in commits

**Comment by ksh168** [comment]
Hey @sahil-ramagiri can you fix it? Open a new issue and continue with your suggested changes.

**Comment by ksh168** [comment]
@rutvikpadhiyar000 next time metion the issue number also in your PR.

**Comment by ksh168** [comment]
@rutvikpadhiyar000  Add your name in main osf repo. Otherwise it will not be shown in contributors.

**Pull request merged**
