### PR TITLE
Added error handling

### LINKED ISSUE #28: Fix crash when optional fields are not supplied
Also add error handling to routes

### PR DESCRIPTION
**Pull request by sahil-ramagiri**
Fixes #28 

image

### CODE REVIEW

**Comment by ksh168** [comment]
Ok, but add a message to tell the user that the custom URL they selected already exists and hence they should select a different one.

**Comment by ksh168** [comment]
Update your PR with it.

**Comment by sahil-ramagiri** [comment]
Added messages

**Comment by ksh168** [comment]
Very nice @sahil-ramagiri 🔥🔥

**Pull request merged**
