### PR TITLE
Set custom_url and original_url length

### PR DESCRIPTION
**Pull request by dheerajd5**
# Description

#44 
Changed the custom_url and original_url length to 64 and 512 resp.

Is this the correct way to do it?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have attached relevant screenshots/videos
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by ksh168** [comment]
@sahil-ramagiri once see to this please.
Also @dheerajd5 it breaks when custom end is not supplied. See to that also.

**Review by sahil-ramagiri — COMMENTED** [review]
just move length checking part after it checks for none

**Comment by dheerajd5** [comment]
> just move length checking part after it checks for none

Is it fine now?

**Review by sahil-ramagiri — COMMENTED** [review]
Yeah now do that in front end too

**Comment by dheerajd5** [comment]
@sahil-ramagiri Sorry, I'm new to this, I didn't understand, I thought the changes I've made will reflect on the front end too right? Like the error message we return in the function. And the front end includes the html files in template?

**Comment by sahil-ramagiri** [comment]
Don't be sorry. You can validate user input on frontend i.e the html templates with maxlength attributes, client side i.e front end validation prevents clients from submitting if they don't pass our conditions.
[https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation) for more info

**Comment by dheerajd5** [comment]
> Don't be sorry. You can validate user input on frontend i.e the html templates with maxlength attributes, client side i.e front end validation prevents clients from submitting if they don't pass our conditions.
> https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation for more info

Okay thanks alot, I have done the required changes to the input of the custom_url and original_url, please verify.

**Comment by sahil-ramagiri** [comment]
Looks good

**Comment by ksh168** [comment]
Nice work!

**Pull request merged**
